#!/bin/bash
# Copyright 2024 Adobe. All rights reserved.
# This file is licensed to you under the Apache License,
# Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
# or the MIT license (http://opensource.org/licenses/MIT),
# at your option.

# Script to generate standalone c2pa.cpp from split source files
# This creates a single file that can be distributed without dependencies

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$SCRIPT_DIR/../src"
OUTPUT_FILE="$SRC_DIR/c2pa.cpp"

echo "Generating standalone c2pa.cpp..."

# Start with the copyright header
cat > "$OUTPUT_FILE" << 'EOF'
// Copyright 2024 Adobe. All rights reserved.
// This file is licensed to you under the Apache License,
// Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
// or the MIT license (http://opensource.org/licenses/MIT),
// at your option.
// Unless required by applicable law or agreed to in writing,
// this software is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR REPRESENTATIONS OF ANY KIND, either express or
// implied. See the LICENSE-MIT and LICENSE-APACHE files for the
// specific language governing permissions and limitations under
// each license.

/// @file   c2pa.cpp
/// @brief  C++ wrapper for the C2PA C library.
/// @details This is used for creating and verifying C2PA manifests.
///          Thread safety is not guaranteed due to the use of errno and etc.
///          C++ standard: C++17
///
///          NOTE: This file is automatically generated from split source files.
///          For development, edit the individual c2pa_*.cpp files and regenerate
///          this file using scripts/generate_c2pa_cpp.sh

#include <cstring>
#include <fstream>
#include <iostream>
#include <string.h>
#include <optional>
#include <filesystem>
#include <system_error>
#include <utility>

#include "c2pa.hpp"

EOF

# Function to extract content between namespace blocks, skipping header and includes
extract_impl() {
    local file=$1
    # Skip everything until we hit 'namespace', then output from there
    awk '
        BEGIN { found_namespace=0; in_header=1 }
        # Skip lines that look like copyright header or includes before namespace
        in_header && /^\/\// { next }
        in_header && /^#include/ { next }
        in_header && /^$/ { next }
        # Once we hit namespace, start outputting
        /^namespace/ { found_namespace=1; in_header=0 }
        found_namespace { print }
    ' "$file"
}

# Add internal header content (detail namespace)
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// Internal detail namespace (from c2pa_internal.hpp)" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Extract detail namespace from internal header
awk '
    BEGIN { in_content=0 }
    /^#include/ { next }
    /^namespace c2pa/ { in_content=1 }
    /^#endif.*C2PA_INTERNAL_HPP/ { exit }
    in_content && !/^#/ { print }
' "$SRC_DIR/c2pa_internal.hpp" >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"

# Add each implementation file
for file in c2pa_core.cpp c2pa_settings.cpp c2pa_context.cpp c2pa_streams.cpp c2pa_reader.cpp c2pa_signer.cpp c2pa_builder.cpp; do
    echo "// ============================================================================" >> "$OUTPUT_FILE"
    echo "// From $file" >> "$OUTPUT_FILE"
    echo "// ============================================================================" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    extract_impl "$SRC_DIR/$file" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
done

echo "Generated $OUTPUT_FILE"
echo "This file can be distributed standalone as c2pa.cpp"
